### ISSUE TITLE
Under sending HN some preconditions are switched around with type 

### ISSUE THREAD

**Issue by mbumedcom** [medcomdk/dk-medcom-hospitalnotification-testscripts#3]
MORS-STOR	R7	Receive: Deceased - deceased during a period of leave	STIN, STOR	 

RE_MORS-emer	R.CORR	Receive: Update Deceased - deceased during acute ambulant	STAA, MORS

**Comment by tmsMedcom** [comment]
@mbumedcom er denne håndteret? https://medcomfhir.dk/ighospitalnotificationtestscripts/testscripts.html

**Comment by mbumedcom** [comment]
Det tror jeg ikke er det med rød ikke precondition til at kunne modtage en Re-mors? 😊
***@***.***
Og det samme her :
***@***.***

Venlig hilsen

Marta Burek
Standardiseringskonsulent
MedCom, Forskerparken 10, 5230 Odense M
Mobi: (+45) 29 10 17 76
***@***.******@***.***>
[Et billede, der indeholder tekst, knojern, clipart, gear  Automatisk genereret beskrivelse]

Fra: tmsMedcom ***@***.***>
Sendt: 10. juli 2023 09:55
Til: medcomdk/dk-medcom-hospitalnotification-testscripts ***@***.***>
Cc: Marta Burek ***@***.***>; Mention ***@***.***>
Emne: Re: [medcomdk/dk-medcom-hospitalnotification-testscripts] Under sending HN some preconditions are switched around with type (Issue #3)


@mbumedcom<https://github.com/mbumedcom> er denne håndteret? https://medcomfhir.dk/ighospitalnotificationtestscripts/testscripts.html
